services:
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: Buses
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3308:3306"
    volumes:
      - storge:/data/db

volumes:
  storge: