spring:
  application:
    name: buses
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # this part is only needed for testing because spring can configure it automatically
  datasource:
    url: jdbc:mysql://localhost:3308/Buses
    username: dev
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: NEVER

logging:
  file:
    name: app.log

jwt:
  public-key: classpath:keys/public.pem
  private-key: classpath:keys/private.pem